version: '3.7'

services:
  postgres:
    container_name: mysql.8.0.32
    image: mysql:8.0.32
    restart: always
    env_file:
      - .env
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    volumes:
      - .:/data
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379


networks:
  webnet:
    driver: bridge
volumes:
  db: